apiVersion: v1
kind: Pod
metadata:
  name: fast-ddpm-brats-pod
spec:
  nodeSelector:
    topology.kubernetes.io/region: us-west
  containers:
    - name: fast-ddpm-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /app/Fast-DDPM-3D
      command:
        - "bash"
        - "-c"
      args:
        - |
          sudo apt-get update && sudo apt-get install -y wget gdown
          
          git clone https://github.com/tsereda/Fast-DDPM-3D.git ${REPO_PATH}
          cd ${REPO_PATH}
          
          source /opt/conda/etc/profile.d/mamba.sh
          mamba create -n fast-ddpm python=3.10.6 -y
          mamba activate fast-ddpm
          
          pip install torch torchvision
          pip install -r requirements.txt
          
          echo "Downloading processed dataset..."
          gdown 1kF0g8fMR5XPQ2FTbutfTQ-hwG_mTqerx
          
          echo "Extracting dataset..."
          unzip -q data.zip
          
          echo "Data structure:"
          ls -la data/
          
          echo "Starting Fast-DDPM training on BraTS..."
          python fast_ddpm_main.py --config brats_linear.yml --dataset BRATS --exp ./experiments --doc fast_ddpm_brats --scheduler_type uniform --timesteps 10
          
          echo "Sampling from trained model..."
          python fast_ddpm_main.py --config brats_linear.yml --dataset BRATS --exp ./experiments --doc fast_ddpm_brats --sample --fid --scheduler_type uniform --timesteps 10
          
          sleep infinity
      volumeMounts:
        - name: git-repo
          mountPath: /app
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 24Gi
          cpu: "12"
          nvidia.com/gpu: "1"
        requests:
          memory: 20Gi
          cpu: "10"
          nvidia.com/gpu: "1"
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  restartPolicy: Never