apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Fast-DDPM-TestData
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: linstor-sdsu 